/**
 * Source unique de vérité pour les chemins REST (aligné avec le backend `routes/api/*`).
 * Quand tu ajoutes une route côté serveur, ajoute le chemin ici et utilise-le via `authApi` / `projectsApi`.
 */

export const paths = {
  health: "/api/health",
  auth: {
    register: "/api/auth/register",
    login: "/api/auth/login",
    logout: "/api/auth/logout",
    refresh: "/api/auth/refresh",
    me: "/api/auth/me",
    verifyEmail: "/api/auth/verify-email",
    verifyEmailCode: "/api/auth/verify-email-code",
    resendVerification: "/api/auth/resend-verification",
    forgotPassword: "/api/auth/forgot-password",
    resetPassword: "/api/auth/reset-password",
  },
  projects: {
    collection: "/api/projects",
    mine: "/api/projects/mine",
    public: "/api/projects/public",
    search: "/api/projects/search",
    byId: (id) => `/api/projects/${id}`,
    comments: (id) => `/api/projects/${id}/comments`,
    deleteComment: (projectId, commentId) => `/api/projects/${projectId}/comments/${commentId}`,
    edit: (id) => `/api/projects/${id}/edit`,
    update: (id) => `/api/projects/${id}`,
    resubmit: (id) => `/api/projects/${id}/resubmit`,
    archive: (id) => `/api/projects/${id}/archive`,
    submitForAi: (id) => `/api/projects/${id}/submit-for-ai`,
    delete: (id) => `/api/projects/${id}`,
  },
  notifications: {
    list: "/api/notifications",
    markRead: (id) => `/api/notifications/${id}/read`,
  },
  users: {
    profile: "/api/users/profile",
    deleteAccount: "/api/users/delete-account",
  },
  admin: {
    projects: "/api/admin/projects",
    users: "/api/admin/users",
    notifications: "/api/admin/notifications",
    markAdminNotificationRead: (id) => `/api/admin/notifications/${id}/read`,
    setUserActive: (id) => `/api/admin/users/${id}/active`,
    reactivateUser: (id) => `/api/admin/users/${id}/reactivate`,
    reports: "/api/admin/reports",
    resolveReport: (id) => `/api/admin/reports/${id}/resolve`,
    validateProject: (id) => `/api/admin/projects/${id}/validate`,
    publishProject: (id) => `/api/admin/projects/${id}/publish`,
    revokeApproval: (id) => `/api/admin/projects/${id}/revoke-approval`,
    retryAi: (id) => `/api/admin/projects/${id}/retry-ai`,
    deactivateProject: (id) => `/api/admin/projects/${id}/deactivate`,
    reactivateProject: (id) => `/api/admin/projects/${id}/reactivate`,
    comments: "/api/admin/comments",
    hideComment: (id) => `/api/admin/comments/${id}/hide`,
    unhideComment: (id) => `/api/admin/comments/${id}/unhide`,
    payouts: "/api/admin/payouts",
    approvePayout: (id) => `/api/admin/payouts/${id}/approve`,
    mockConfirmPayout: (id) => `/api/admin/payouts/${id}/mock-confirm`,
    failedNotifications: "/api/admin/failed-notifications",
    retryNotification: "/api/admin/retry-notification",
    opsFailedRefunds: "/api/admin/ops/failed-refunds",
    opsFailedPayouts: "/api/admin/ops/failed-payouts",
    opsRetryRefunds: "/api/admin/ops/retry-refunds",
    opsRetryPayouts: "/api/admin/ops/retry-payouts",
  },
  investments: {
    create: "/api/investments",
    mine: "/api/investments/mine",
    cancel: (id) => `/api/investments/${id}/cancel`,
    retry: (id) => `/api/investments/${id}/retry`,
    mockConfirm: "/api/investments/mock/confirm",
  },
  reports: {
    create: "/api/reports",
    createComment: "/api/reports/comments",
    mine: "/api/reports/mine",
  },
  payouts: {
    mine: "/api/payouts/mine",
    byId: (id) => `/api/payouts/${id}`,
    bankDetails: (id) => `/api/payouts/${id}/bank-details`,
  },
  recommendations: {
    list: "/api/recommendations",
  },
  chatbot: {
    askProject: (id) => `/api/projects/${id}/chat`,
  },
};
